# Generated by Django 5.1.5 on 2025-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_num", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apt_num", models.TextField()),
                ("zip_code", models.IntegerField()),
                ("dob", models.DateField()),
                ("dor", models.DateField()),
                ("party", models.CharField(max_length=1)),
                ("precinct_num", models.IntegerField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
