# Generated by Django 5.1.5 on 2025-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_precinct_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="dob",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="dor",
            field=models.TextField(),
        ),
    ]
