# Generated by Django 5.1.5 on 2025-04-13 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_company_stock_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bucket",
            name="companies",
        ),
        migrations.CreateModel(
            name="BucketCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.bucket"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.company",
                    ),
                ),
            ],
        ),
    ]
