# Generated by Django 5.1.5 on 2025-04-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_remove_bucket_companies_bucketcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="bucket_symbol",
            field=models.CharField(default="ABC", max_length=4),
            preserve_default=False,
        ),
    ]
