# Generated by Django 5.1.5 on 2025-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_bucket_bucket_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="bucket",
            name="price_per_share",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
