# Generated by Django 5.1.5 on 2025-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cash_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="stock_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="market_cap",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
