# Generated by Django 5.1.5 on 2025-04-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_customer_cash_value_customer_stock_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares_purchased", models.IntegerField()),
                ("purchase_date", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.customer",
                    ),
                ),
            ],
        ),
    ]
