# Generated by Django 5.1.5 on 2025-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_investmentcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucket",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
