# Generated by Django 5.1.5 on 2025-04-20 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_bucket_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_updated",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 4, 20, 2, 56, 3, 472573, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
