# Generated by Django 5.1.5 on 2025-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_customer_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
