# Generated by Django 5.1.5 on 2025-03-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_image_statusimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusimage",
            name="profile",
        ),
        migrations.AddField(
            model_name="statusimage",
            name="status_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mini_fb.statusmessage",
            ),
        ),
    ]
