# Generated by Django 5.1.5 on 2025-03-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0004_remove_statusimage_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusimage",
            name="status_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mini_fb.statusmessage"
            ),
        ),
    ]
